FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Searchflight

Searchflight is a robust API that enables you integrate flights search and bookings into your app.


## Authentication [/token]

### Get Token [POST]

Searchflight expects for a authorization token to be included in all requests as a header.
+ Request (application/json)

        {
            "api_key": "lQKF8n1KVYezN7MDTMqxhXGrZCfgRDvQ",
         }
+ Response 201 (application/json)


    + Body

            {
                "status": "200",
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQwLCJuYW1lIjoic2F2YW5hIHNtYXJ0c2F2ZSIsImFjY291bnROdW1iZ",
            }


## Get city code from name [/cities]

### Get city code from name [POST]
With this endpoint you can get the IATA city codes associated with a particular city name.

+ Request (application/json, )
    + Headers

            Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQwLCJuYW1lIjoic2F2YW5hIHNtYXJ0c2F2ZSIsImFjY291bnROdW1iZ

    + Body
                    
            {
                 "city_name": "Uyo,
            }
+ Response 201 (application/json)


    + Body

            {
                "status": "200",
                "data": [
                    {
                        "city_code": "QUO",
                        "city_name": "Uyo",
                        "country": "Nigeria"
                        
                    }, {
                        "city_code": "PSR",
                        "city_name": "Uyo",
                        "country": "Switzerland"
                    }, {
                        "city_code": "WDV",
                        "city_name": "Uyo",
                        "country": "Algeria"
                    }
                ]
            }
+ Response 401 (application/json)


    + Body

            {
                "status": "401",
                "data": "Unauthorized access"
            }
+ Response 404 (application/json)


    + Body

            {
                "status": "404",
                "data": "resource not found"
            }


## Get city name from code [/cities{city_name}]

### Get city name from code [GET]
With this endpoint you can get the city name associated with an IATA Code.
Searchflight expects for a authorization token to be included in all requests as a header.
+ Request (application/json, )
    + Headers

            Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQwLCJuYW1lIjoic2F2YW5hIHNtYXJ0c2F2ZSIsImFjY291bnROdW1iZ

+ Response 201 (application/json)


    + Body

            {
                "status": "200",
                "data": [
                    {
                        "city_code": "QUO",
                        "city_name": "Uyo",
                        "country": "Nigeria"
                        
                    }
                ]
            }
+ Response 401 (application/json)


    + Body

            {
                "status": "401",
                "data": "Unauthorized access"
            }
+ Response 404 (application/json)


    + Body

            {
                "status": "404",
                "data": "resource not found"
            }